### ISSUE TITLE
Support Geometry Collection / Feature Collection

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#114]
Currently `sentinelsat` only supports a single geometry per given GeoJSON or WKT. From a users perspective I would expect the behaviour to be that the search happens over all geometries if I provide a geojson with Feature Collection or a WKT Geometry Collection and the results are concatenated.

Would you agree with this design choice?

This would be a simple refactoring that introduces a loop over all geometries provided by the user.

**Comment by j08lue** [comment]
Can the Copernicus OA Hub API perhaps take a `FeatureCollection` of some kind, too?

**Comment by valgur** [comment]
Sounds useful, I would add this. I did a quick test and the server appears to support WKT's `GEOMETRYCOLLECTION` type: https://scihub.copernicus.eu/dhus/search?format=json&rows=10&q=footprint:%22Intersects(GEOMETRYCOLLECTION(POINT(4%206),LINESTRING(4%206,7%2010)))%22

**Comment by Fernerkundung** [comment]
Great find @valgur! So I'll just need to refactor `geojson_to_wkt` to produce WKT `GEOMETRYCOLLECTION` from GeoJSON's `FeatureCollections`.

**Comment by mackland** [comment]
@Fernerkundung  @valgur  Wouldn't mind picking this one up to get to v1.1. I made a contribution last year regarding quicklooks but unfortunately haven't had much time since.

Had a look at wkt.py and to let wkt.dumps() do most of the work it seemed easier to rewrite the input if its a Geometry/FeatureCollection since the new dict can be passed directly to wkt.dumps() and parsed as expected. 

Quick test just to demonstrate idea:
```
geojson_obj = read_geojson('test_geojson.geojson')

geojson_obj_collection = dict()
geojson_obj_collection['type'] = 'GeometryCollection'

geoms = []
for feature in geojson_obj['features']:
    geoms.append(feature['geometry'])
geojson_obj_collection['geometries'] = geoms

wkt = geomet.wkt.dumps(geojson_obj_collection, decimals=decimals)
```
which lets wkt.dumps do the heavy lifting and returns for multiple shapes/types as expected:
```
GEOMETRYCOLLECTION (
POLYGON ((11.5356 52.5630, 11.1841 52.2950, 11.6455 51.9307, 11.9751 52.0930, 11.9971 52.4828, 11.5356 52.5630)),
POLYGON ((12.6562 52.4024, 13.8428 52.4024, 13.8428 52.7895, 12.6562 52.7895, 12.6562 52.4024)),
LINESTRING (9.5142 51.9578, 10.2832 51.4129),
POINT (9.6680 52.7363)
)
```
Let me know if you're happy with this I'll open a PR

**Comment by j08lue** [comment]
> Let me know if you're happy with this I'll open a PR

Sounds like the right solution, @mackland! We would welcome a PR for that.
