### ISSUE TITLE
Incorrect geometries of footprints which cross the 180 meridian.

### ISSUE THREAD

**Issue by lpd2** [sentinelsat/sentinelsat#149]
There is an error with the geometries of footprints which cross the 180 meridian, when displayed they appear stretched across the whole globe. Here are a few product ID's affected by this:

1cc696ac-3e2a-4a4e-b9e2-efc27568ef23
68926bb8-f522-4065-9c5f-c8376e7ae5f9
b666586e-f876-48b5-9838-05097fde0b24
7a12cbfb-85ef-4166-baa4-82068ebf4670
982f9efc-dd90-4981-9189-960937180922
da310473-69c5-4bc1-afa4-00177852c188

I believe this issue is due to having a mixture of positive and negative x coordinates in the geometry, and can be solved by replacing the negative values with values greater than 180.

**Comment by valgur** [comment]
The coordinate values in the footprint geometries are perfectly correct in this case. The issue is more related to how your specific GIS software handles geometries that cross the dateline. One easy way to 'fix' this would be to use a different map projection, for example.
So I would not quite call this a bug, but making sure that none of the longitude values in a geometry do not wrap is a reasonable workaround that should work well for most GIS software and I'd say we should consider including this in `sentinelsat`.

**Comment by Fernerkundung** [comment]
So the "fix" would be to save the footprints in a different projection?

**Comment by j08lue** [comment]
You just need to either add or subtract 360 to parts of the sequence to make it continuously increasing.

This is how I did it once with Numpy arrays:

```python
    breaks = np.where(np.diff(c) < 0)[0]
    for i in breaks:
        c[:i+1] -= 360
```
Without Numpy, we will need some more looping...

**Comment by valgur** [comment]
> So the "fix" would be to save the footprints in a different projection?
No, simply changing the overall Project CRS (to some UTM zone perhaps) in QGIS should be enough, for example.
Actually, now that I tested this again, I noticed that the footprints are clipped at the meridian line. So disregard that suggestion.
