### ISSUE TITLE
other options are ignored when using `--name`

### ISSUE THREAD

**Issue by justinkotzebue** [sentinelsat/sentinelsat#170]
I'm facing a problem using `sentinelsat` v0.12.1 via command line for Sentinel 2. When I choose the addional option `--name *R051*`, other options like `--start --geometry` are beeing ignored and all products from the relative path (R051) get downloaded. Is that a known issue? Or do I maybe use it not the right way?

**Comment by j08lue** [comment]
As far as I can see in the [relevant lines of the cli definition](https://github.com/sentinelsat/sentinelsat/blob/b5e986d24e5ce4bb809356612cabb8109ea655cd/sentinelsat/scripts/cli.py#L129-L131), we always include all specified parameters in the query, even when `name` aka `identifier` is specified.

So if you experience that other parameters are ignored, then this must be happening on the server. If that is the case, we should reflect the behaviour of the server in our client and warn the user that his additional parameters will be ignored.

Since you can use glob patterns with `identifier`, I would intuitively expect that it can be used together with other keywords. But the server might be following a different logic?

**Comment by valgur** [comment]
This looks like a shell escaping issue to me. I suspect that `--name *R051*`, which is not enclosed by single quotes, gets expanded to no matching files, which alters the meaning of the remaining query. That is, the parameters get interpreted as `--name=--start`.

I'm closing this as a quite old issue, but feel free to reopen this if you have any thoughts or remaining issues regarding this @justinkotzebue.
