### ISSUE TITLE
Strange error: 401

### ISSUE THREAD

**Issue by coconutattitude** [sentinelsat/sentinelsat#188]
I'm trying a command you provided in sentinelsat quickstart

sentinelsat -u "johnson" -p "secretpass" -g "try1.json" -s 20160101 -e 20160131 --sentinel 2 --cloud 40 -d

and I can't access the database and Im having this error: 
sentinelsat.sentinel.SentinelAPIError: HTTP status 401 Unauthorized:
# HTTP Status 401 - Full authentication is required to access this resource

**message** _Full authentication is required to access this resource_

 **description** _This request requires HTTP authentication._

But when I log in the website everything is ok. whats the problem here?

**Comment by Fernerkundung** [comment]
What happens if you try: `sentinelsat -u user -p pass -g "try1.json" -s 20160101 -e 20160131 --sentinel 2 --cloud 40 -u https://scihub.copernicus.eu/dhus` ?

When you use the website you are redirected to the `/dhus` endpoint. The default for `sentinelsat` is the `/apihub` endpoint. Synchronization of accounts might take some time. Is you account newly created by any chance?

**Comment by Fernerkundung** [comment]
Closed due to inactivity. If the problem persists please tell us and we'll reopen the issue.

**Comment by pugsley** [comment]
Just a quick note, I had the same issue and it was fixed by adding `--url https://scihub.copernicus.eu/dhus`. I'd only just created my account so it must've been the syncronization issue.
