### ISSUE TITLE
Download by 'Name' instead of ID?

### ISSUE THREAD

**Issue by jdries** [sentinelsat/sentinelsat#191]
Currently downloads are always by uuid. However, the different endpoints (apihub, colhub and colhub2) use different id's for the same product.
The OData protocol also allows us to query product info by Name, like this:
https://colhub2.copernicus.eu/dhus/odata/v1/Products?$filter=substringof(%27S1B_IW_GRDH_1SDV_20180318T172340_20180318T172405_010089_0124EE_325B%27,Name)&$top=5&$format=json
Hence it would be quite easy to implement a download by name, which would be useful when trying to fallback to different endpoints when trying to download the same product. 
I could provide a pull request if needed, would you be interested?

**Comment by j08lue** [comment]
We already have the `sentinelsat --name` [option](https://github.com/sentinelsat/sentinelsat#options). And you can always use `--query` to search by other keywords supported by DHuS.

Does any of these already do what you want?

**Comment by j08lue** [comment]
Or did you mean the API method?

https://github.com/sentinelsat/sentinelsat/blob/22bbd5aac4d7715a5a17d89b7e0aac2089f6cbdc/sentinelsat/sentinel.py#L386-L415

**Comment by j08lue** [comment]
If you were referring to the API, I think the solution should be that you translate the names into IDs yourself using 

```
products = api.query(identifier='your-identifyer-pattern'))
product_id = list(products)[0]
```

**Comment by jdries** [comment]
I was referring to the API method, so basically adding a method:
def download_by_name(self, name, directory_path='.', checksum=True)

and a second helper method:
def get_product_odata_by_name(self, name, full=False):

I agree that your workaround would also solve this, so this is mostly about added convenience, and reducing the number of requests to the hubs.

**Comment by Fernerkundung** [comment]
I fail to see how this would reduce the number of requests to scihub. `download_by_name` would still need to perform a search first to translate the name to UUID, as that is necessary to get the download url.

I can see the potential to add convenience - keep in mind however, that there is a good reason that we kept UUID instead of names: names are not always unique and there are cases on DHuS endpoints where the same name is listed under 2 different UUIDs - see #125

**Comment by jdries** [comment]
Basically in the current situation it would be:

- Search by name (1 api call)
- Download (by id) (2 api calls)
The improvement (download_by_name) would be 2 calls:

1. Look up download url: https://scihub.copernicus.eu/dhus/odata/v1/Products?$filter=substringof(%27S2A_MSIL1C_20170205T105221_N0204_R051_T31TCF_20170205T105426%27,Name)&$top=5&$format=json&$orderby=IngestionDate
2. Actual download

Indeed, there's the issue with multipe files having the same name. Would ordering by IngestionDate to resolve that? (Unfortunately the product referenced in my example no longer seems to be associated with two uuid's.)

**Comment by Fernerkundung** [comment]
Sorry for the late reply @jdries, I totally missed that this enhancement proposal is still open.

In summary, your proposal would add convenience and reduce API calls to the DHuS endpoint.

This would enable the download with:
```python
api.download_by_name(name="S2MSI_example")
```

instead of:
```python
product = api.query(identifier="S2MSI_example"))
api.download(product)
```

I don't really see a lot of added convenience, especially since the existing functionality can be shortened to one line as well. The API calls are reduced from 3 to 2 - which is good, but I don't think they make that much of a difference at the DHuS endpoint. I don't feel this warrants the addition of code, that has to be tested and supported in the future.

However, that is just my opinion and since this project follows an open meritocracy model I would love see other voices from the community or developers on this (pinging @j08lue @valgur).

PS: You hinted at this being useful to search/download from multiple DHuS endpoints. That is an addition I would see as very useful - ideally with the ability to create lists and hierarchys of endpoints each user prefers. A common use case might be that a user is querying his national data endpoint first, then a central DHuS and in last place a long-term archive (once central DHuS will switch to a rolling archive).

**Comment by j08lue** [comment]
Thanks for picking this up, @Fernerkundung. I agree with you that this is too much additional code for the modest convenience it adds. But good suggestion @jdries - please, do keep them coming!

**Comment by valgur** [comment]
I agree with everything @Fernerkundung and @j08lue have already said. I just wanted to add that I have found the OData API to be not at all optimized for search queires like this, compared to the OpenSearch/Solr interface.

A quick experiment (I'm using a random string in place of a product name to avoid caching):
```python
%%timeit
id = randint(1, 1e9)
api.session.get(f'https://scihub.copernicus.eu/dhus/odata/v1/Products?$filter=substringof(%27{id}%27,Name)&$top=5&$format=json&$orderby=IngestionDate%20desc')
```
20.2 s ± 5.46 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

```python
%%timeit
id = randint(1, 1e9)
api.query(identifier=f'*{id}*')
```
1.74 s ± 203 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by jdries** [comment]
Thanks for providing your feedback, I'll close this issue!
