### ISSUE TITLE
excluding products already available offline from SentinelAPI.download_all

### ISSUE THREAD

**Issue by NiklasKeck** [sentinelsat/sentinelsat#192]
Good day,
I have been using sentinelsat for quite a while and had to script my way around one limitation:
When using the` SentinelAPI.download_all` with the result of the `query` method (the uuids) as input there is no convenient way to skip specific products without manually filtering this `products` input list. I would love to see this feature in `sentinelsat ` and have implemented it in my local repo. Mabye its a helpful addition for other users as well? 
So here is what I propose:
A new argument to `SentinelAPI.download_all` called `skip_products` that takes as input a list of uuids and/or root folders of products to skip and filters them out from the input argument `products`.

Just to elaborate on why I deem this feature important:
I am working on windows using SARscape to regularly process relatively large stacks of Sentinel-1 data with constant region, sensor, accquisition mode etc (excluding a temporal constraint). Within this workflow I need to unzip and rename the obtained products. I regularly want to download recently published products using the same query. The problem is: Even if I choose the same output directory, all the products that where already downloaded would be downloaded again, since only products with exactly the same filename (local vs. online) are skipped.
Thanks a lot by the way for the great library!

**Comment by Fernerkundung** [comment]
This sounds like a compelling addition to the examples in the documentation. I can see the periodic querying for newly added products as a common use case.

However, I don't think adding `skip_products` adds to the useability of `sentinelsat` for two reasons:

- constructing the list of products to skip is something every user has to do on their own anyway - some may keep a database, others a textfile, etc. Currently we can include the functionality to skip existing, full sized downloaded products in a single directory. Including every other way to check for existing products would be a rather complicated endeavour.

- filtering the products list is a single dict comprehension. I don't think hiding that behind a sentinelsat function adds to the goal of being a Pythonic interface to DHuS.

For instance if you have the downloaded products as unzipped folders one could do something like this:

```python

products = api.query()
skip_products = glob.glob("/Sentinel-1/unzipped/S1A*")

filtered_products = {k:v for k,v in products.items() if v['filename'] not in skip_products}
```

That beeing said, we are sorely lacking more examples for common use cases such as yours in the docs and you are more than welcome to contribute :+1:

**Comment by NiklasKeck** [comment]
That is a good point: There is an enormous amount of different ways one could organize their data. But I think the most common case might be just in plain folders. On windows the path names also have to be changed as they are too long for the file system. This results in the loss of the correct filename so the example you provided would not work anymore.

The problem is that figuring out the uuid from such a folder with a random name is not trivial and might better be implemented within sentinelsat (cp. my pull request).

**Comment by Fernerkundung** [comment]
I still think the PR is too much tailored towards a specific, specialized use case. I see the appeal of removing a list of products, hence my example, but can you argue that *most* people would mangle the folder names because they have to use the old file name convention *and* are on windows *and* keep the inspire.xml or the products pdf?

For me that are too many specific assumptions to be included as a generalized function. Then again that is just my opinion - maybe @valgur @j08lue or @willemarcel want to chime in?

**Comment by j08lue** [comment]
I agree with you, @Fernerkundung, that your use case, @NiklasKeck, is not not generic enough to account for it in the library. 

If this way of organizing the files was canonical (e.g. explicitly recommended by SciHub) or made particularly more sense than others, we should consider supporting it. But I think it is just one way of very many - certainly sensible, but so are many others.

This is a perfect case for when to use the API rather than the CLI: when you need your own logic e.g. for filtering the results between query and download. It would be great to see a PR adding this as an example to the docs.

**Comment by NiklasKeck** [comment]
Thank you for the comments @Fernerkundung and @j08lue. That sounds reasonable. I will work on a PR to add this as an example to the docs instead.
