### ISSUE TITLE
number of products returned by _parse_opensearch_response(products) is different to incoming products list

### ISSUE THREAD

**Issue by pfreimuth** [sentinelsat/sentinelsat#200]
_parse_opensearch_response(products) reformats the query result in query() 
set but it seems that there is a paging problem so the length of the orderedDict is in most cases exactly 100 or sometimes below (depending on length of products list). 
As 100 is the configured self.page_size it seems to me that the last page get somehow ignored.

**Comment by pfreimuth** [comment]
i guess the main reason for the reduction is that there are multiple records in the products list having the same prod['id'] u'58b132d4-dfac-455b-b640-6f2b76e012a5'  so the next appearance overwrites the already existing one. Its unclear to me why this can happen.

**Comment by pfreimuth** [comment]
api.query uses the following params as an example:
{'ingestiondate': ('2017-08-01T00:00:00Z', '2017-09-01T00:00:00Z'), 'platformname': 'Sentinel-1', 'producttype': 'GRD', 'area': 'POLYGON((117.5000 41.0000,117.5000 31.0000,127.5000 31.0000,127.5000 38.5000,133.0000 38.5000,133.0000 43.3000,127.2000 43.3000,127.2000 41.0000,117.5000 41.0000))'}
i get 186 results from api.query() but after _parse_opensearch_response(products)  the ordered dict contains only 100 elements.

**Comment by pfreimuth** [comment]
OK, i traced down the problem and the misbehaviour gets introduced by the usage of a order_by.
In my case i used order_by="ingestiondate". 
I have seen similar problems on our own eleastic-search client when using a sort_by param of type datetime and having a resultset that needs to be read in pages. 
If i avoid using order_by i do not get duplicates in the returned product list and _parse_opensearch_response(products)  does not eliminate records due to duplicate prod_ids.

**Comment by Fernerkundung** [comment]
Thank you for reporting this bug with such an extensive description - this really helps in reproducing it. I started a Jupyter Notebook for easier reproduction: https://gist.github.com/Fernerkundung/f7944853ed12523ba46fa353db262e4f

For documentation, this would be the URL to query results 101-183 ordered by `ingestiondate` - `https://scihub.copernicus.eu/apihub/search?q=producttype:GRD%20AND%20footprint:%22Intersects(POLYGON((117.5000%2041.0000,117.5000%2031.0000,127.5000%2031.0000,127.5000%2038.5000,133.0000%2038.5000,133.0000%2043.3000,127.2000%2043.3000,127.2000%2041.0000,117.5000%2041.0000)))%22%20AND%20ingestiondate:%20[2017-08-01T00:00:00Z%20TO%202017-09-01T00:00:00Z]&rows=100&start=100&orderby=ingestiondate%20asc`

This looks like a valid response to me, so I suspect the error is with `sentinelsat` when it parses the the pages. The weird thing is, as you pointed out, that there is no parsing/pageination issue when the `order_by` option is left out.

Even weirder still, the parameter selected for ordering influences the amount of products returned by `query()`:

- it seems like date time objects return 100 products, i.e. only the first page - this relates to `beginposition`, `ingestiondate` and `endposition`
- `orbitnumbers` return 134 and `relativeorbitnumbers` 136 products
- string objects return 115 products, except `filename` which returns 132
- `cloudcoverpercentage` also returns 115 products even though it is not present/empty in Sentinel-1 metadata

polarisationmode : 115
producttype : 115
filename : 132
lastorbitnumber : 134
sensoroperationalmode : 115
relativeorbitnumber : 136
swathidentifier : 115
beginposition : 100
endposition : 100
cloudcoverpercentage : 115
ingestiondate : 100
orbitnumber : 134
platformname : 115
lastrelativeorbitnumber : 136
orbitdirection : 132

I'm unable to identify a meaningful pattern here, especially since the URLs themselves seem to work fine.

**Comment by valgur** [comment]
Nice work, @Fernerkundung! Based on the above it looks like the bug is in [sentinel.py:252](https://github.com/sentinelsat/sentinelsat/blob/master/sentinelsat/sentinel.py#L252):
```python
ret = self._load_subquery(query, limit=new_limit, offset=new_offset)[0]
```
which is missing the `order_by` argument.
In other words, the first subquery is executed correctly, but any consecutive ones not.
