### ISSUE TITLE
Clarify API usage example in the docs

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#229]
Based on #227, we should make it more clear in the docs that `search_polygon.geojson` is a file you must provide.

**Comment by psal93** [comment]
Hi there, I am going to contribute to solving this issue.  I'm pretty new to open source development, so I figure this issue would be a gentle introduction.

**Comment by Fernerkundung** [comment]
Hi @psal93,

This issue is a good start indeed. Once you make the according changes in the `docs` folder you can build the documentation locally with Sphinx. If everything looks OK, create a Pull Request with your changes. If you haven't already please also take a look at [CONTRIBUTE.rst](https://github.com/sentinelsat/sentinelsat/blob/master/CONTRIBUTE.rst)

**Comment by psal93** [comment]
@j08lue indeed it is! I found this repo while browsing some of the [Hacktoberfest]( https://hacktoberfest.digitalocean.com) resources.
