### ISSUE TITLE
error message when using geojson file with longitudes outside 180:-180

### ISSUE THREAD

**Issue by anngitta** [sentinelsat/sentinelsat#232]
Hi,
I made polygon using the site recommed in Sentinelsat Documentation (http://geojson.io/#map=4/60.63/370.28), but I got an error message when using the saved file with sentinelsat, see below.

`sentinelsat.sentinel.SentinelAPIError: HTTP status 200 OK: Invalid query string. Check the parameters and format`

I'm using:
`sentinelsat -u myusername -p mypassword -g mypath\map.geojson --sentinel 2 -d`

I manage to download Sentinel-2 files when excluding the geojson file. Is there something wrong with how the file is written?

**Comment by valgur** [comment]
Since the problem seems to be related to the GeoJSON file you are using, could you please share it? You can upload it as a [Gist](https://gist.github.com/), for example, or paste the contents here if it's not too big.

**Comment by anngitta** [comment]
Yes, I just made a polygon in geojson.io and saved the file as geosjon. I've copied it from Notepad++ below. 

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[359.73632812499994,72.91963546581484],[363.8671875,57.040729838360875],[369.580078125,57.040729838360875],[391.201171875,69.90011762668541],[395.947265625,72.81607371878991],[359.73632812499994,72.91963546581484]]]}}]}

**Comment by valgur** [comment]
Thanks!
The problem appears to be caused by the longitude values that are not in the range of -180...180, which SciHub does not accept (but does not provide any meaningful error message for either).

As an immediate fix you could try adjusting the longitude values. I'm not sure whether SciHub handles footprints that cross the 180-th meridian correctly, though.

**Comment by anngitta** [comment]
Great, thanks, I will have a look at it tomorrow.
Anna Birgitta

**Comment by j08lue** [comment]
> I'm not sure whether SciHub handles footprints that cross the 180-th meridian correctly, though.

If that becomes a problem, you could submit a `FeatureCollection` with two features, one on each side.

**Comment by Fernerkundung** [comment]
>If that becomes a problem, you could submit a FeatureCollection with two features, one on each side.

In the CLI you can't as the first feature in a collection is used by default. (Unless I missed a change and the [docs](https://sentinelsat.readthedocs.io/en/stable/api.html?highlight=read_geojson) are wrong)

**Comment by valgur** [comment]
Actually, it should work with a single file right now, if you use a MultiPolygon instead of two Polygons, I think.

Anyway, I suggest we add a check in `geojson_to_wkt()` for coordinates outside the -180...180 range and throw an exception. This would be quite helpful since the response from server is totally useless in this case.

**Comment by Fernerkundung** [comment]
> add a check in `geojson_to_wkt()` for coordinates outside the -180...180 range and throw an exception
+1 from me

You are right about the MultiPolygon working as well, as long as it is the first feature in the FeatureCollection (when using the CLI).
