### ISSUE TITLE
Adding support for Long Time Archive access?

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#233]
SciHub [just rolled out](https://scihub.copernicus.eu/news/News00382) a new Long Time Archive (LTA) access service. More detailed documentation is available [here](https://scihub.copernicus.eu/userguide/LongTermArchive).

The relevant details of interest to us are:
* Addition of a new OData field `Online`, which is `false` for archived products. We should definitely add this to the dictionary returned by `get_product_odata()`.
* No corresponding OpenSearch field is provided.
* Triggering of the retrieval of offline products is simply done by GET-ing the normal download URL of the product.
* Information about a retrieval being triggered and its success status is provided via [a HTML status code plus the `cause-message` header](https://scihub.copernicus.eu/userguide/LongTermArchive#HTTP_Status_codes) (which we are already using in our error messages). I'm not yet sure how to handle these, but we probably should take these into account in the code. In particular, the `202: Accepted` status code will likely cause problems for the current code, since it will not raise an exception, I think.
* There is no system to get notified about a product becoming available except for checking the OData for changes.

Adding tests for these will be slightly more difficult also, since we can't allow our code to trigger retrievals unnecessarily and their state is not constant either, so we'd need to add some mock responses.

Also, I currently do not see any LTA products being listed in SciHub: https://scihub.copernicus.eu/apihub/odata/v1/Products?$filter=Online%20eq%20false

**Comment by Fernerkundung** [comment]
+1 to everything you proposed.

I would add that we deliver a message (CLI) or log a warning (Python) when a user tries to download a set of products of which some or all are offline.

When our download function triggers the LTA retrival via an attempted GET (without failing due to the error message) a message to the users could simply be triggered by checking the product dict containing >= 1 `online=False` products prior to download:

"Your download query contains LTA products that are retrieved from the archive. To download them run the same query some time later."

Our logic of not overwriting existing products should handle the rest. I'm still not sure what time to include in the message as ESA only states "within minutes to hours" which is not very helpful.

>Also, I currently do not see any LTA products being listed in SciHub: https://scihub.copernicus.eu/apihub/odata/v1/Products?$filter=Online%20eq%20false

The first offline products are appearing as we speak - most of them Sentinel-1 SLC or RAW.

**Comment by andretheronsa** [comment]
Is there any update on this?
How should I go about downloading from the LTA using Sentinelsat currently? 
Is there a flag to toggle when using api.download() ?
Currently my downloads start momentarily, instantly stops and the MD checksum fails and the temp file is deleted. I think this is because the product is in LTA...

**Comment by Fernerkundung** [comment]
Can you try to call `api.download()` again after a short wait period? 

The retrieval from LTA to the online archive should be triggered automatically if you attempt to download. The download is then possible as soon as the data is back in the online archive. If you try the same query again after a short wait period you should be able to download the products, minus the ones that you already downloaded, as checked by sentinelsat.

If that works this would be the current workaround, until this issue is adressed.

**Comment by andretheronsa** [comment]
Yes, it seems to work after the file has been bought online.
It would be useful to be able to check whether a file is available online or offline and if offline then TRY again after increasingly long sleep intervals (1minute/1hour/10hours/24 hours).
I see the api.query() does not return the online status of the product and an Odata query must be done to get its status (https://scihub.copernicus.eu/userguide/LongTermArchive). However, using the API I do not see the online status returned (api.get_product_odata('bb6db0c9-98a9-4b69-a559-57a3f954d73f', full=True)

Is there anyway to query the online status through Sentinelsat?
This may help: "The OData API returns an HTTP status code 202 Accepted when a request is successfully submitted to the LTA."

Sorry if these are simple questions - I am still quite new to python odata queries etc.

**Comment by valgur** [comment]
[_parse_odata_response](https://github.com/sentinelsat/sentinelsat/blob/master/sentinelsat/sentinel.py#L1044) needs updating to support LTS info. The `Online` field is currently not read from the server's response. Maybe should add `CreationDate` and `IngestionDate` as well, since they are not identical anymore for LTS products, it appears.

**Comment by Kay0777** [comment]
I'm trying to get LTA OData with python module sentinalsat.
Unfortunately, I can't  do this.
When I try to download data with products id system returns error like this:
"""Product 553fad04-9502-4cae-8dc4-1dd747beb769 is not online. Triggering retrieval from long term archive.
Traceback (most recent call last):
  File "download.py", line 40, in <module>
    api.download(id=products_id[0])
  File "C:\Users\Kayrat\AppData\Local\Programs\Python\Python37\lib\site-packages\sentinelsat\sentinel.py", line 588, in download
    self._trigger_offline_retrieval(product_info["url"])
  File "C:\Users\Kayrat\AppData\Local\Programs\Python\Python37\lib\site-packages\sentinelsat\sentinel.py", line 654, in _trigger_offline_retrieval
    with self.session.get(url, auth=self.session.auth, timeout=self.timeout) as r:
AttributeError: __enter__""

Please, Help me
Thanks!

**Comment by Fernerkundung** [comment]
@Kay0777 This is not relevant to this issue, which has been closed already.

If you encounter an error please open a new issue and provide the necessary info to reproduce the error: product id, query, which DHuS url you are targetting, which version of sentinelsat you are on, etc.
