### ISSUE TITLE
Dump the query result to a file?

### ISSUE THREAD

**Issue by elmerehbi** [sentinelsat/sentinelsat#245]
Is it possible to dump the results of a query into a text file? Piping didn't work.

**Comment by j08lue** [comment]
> Piping didn't work.

How? Why would it not? Can you please send an example command (with the piping you tried) and some details - Linux/Windows...?

You could also use the Python API and write the query results to a file in exactly the way you want. You can see here how the CLI function writes the result (logging):

https://github.com/sentinelsat/sentinelsat/blob/df40891ea5bccb70f716c92e30674066f00cc1e7/sentinelsat/scripts/cli.py#L163-L168

You could mimick that, if you want the same format, just writing to a file instead of the `logger.info` calls.

**Comment by Fernerkundung** [comment]
I am assuming a query performed with the CLI? What exactly are you trying to achieve and what do you want to dump into a file for that?

You can dump the footprints and metadata of each scene with the `--footprints` option.

**Comment by elmerehbi** [comment]
Here's an example:

**Comment by j08lue** [comment]
With `--footprints`, you already get the results as a nice JSON file `search_footprints.geojson` in your current directory. Does that format not work for you?

You did not yet answer the following question: What do you actually want to achieve - what do you want to use the dumped query results for? It might be this piping stuff is not actually what you need. We might be able to help better if we know what your original problem is.

But to answer your question: We use `logging` for our console output and that by default outputs to `stderr`. When you use `>` to pipe, you get `stdout` only. So if you really want to pipe the output, you can redirect `stderr` like this:

```
sentinelsat -s 20181024 -e 20181025 --producttype SLC --sentinel 1 2> query.txt
```

which works on Linux and is [supposed to work also on Windows](https://support.microsoft.com/en-us/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout), but in my test it did not.

However, you will also get the status bar in the text file and it won't look pretty.

**Comment by Fernerkundung** [comment]
@j08lue the bit about our `stderr` logging and how to pipe it into a text file (e.g. for troubleshooting) might be a good addition to the docs. Do you think a "CLI/ More examples" section might be helpful (analogue to the API examples section)?
