### ISSUE TITLE
Why do my SciHub credentials work on /dhus but not on /apihub?

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#260]
We frequently encounter users of sentinelsat who ask why their Copernicus Open Access Hub account works against https://scihub.copernicus.eu/dhus, but not (yet) works against https://scihub.copernicus.eu/apihub. This is the case both for newly created accounts and those that changed password and the delay seems to be days to weeks.

So why is it, actually, that credential changes take so long to propagate to `/apihub`? And why do you have two separate endpoints at all?

**Comment by j08lue** [comment]
I asked Copernicus EO Support that and the Data Hubs team replied:

> User credentials are made valid to access the API Hub within 1 week from the registration on SciHub.
> Moreover, any modification performed by the user on the SciHub account (e.g. new password, e-mail, country, etc.) is transferred to API Hub within 1 week from the update.

So, sadly, the only message is: The delay is a fact. Accept it. 🌹

**Comment by Fernerkundung** [comment]
Would it be reasonable for us to make `dhus` the default target API then? It seems that the days of frequent downtimes are gone and pointing users to an answer by the support team which is nowhere to be found in their documentation creates a lot of unnecessary friction. Expecting a week of wait time without including that in the official documentation is frankly unacceptable.

I vote to change the default API endpoint to `dhus`, as I don't see the issues persisting that warranted the change to `apihub`.

**Comment by j08lue** [comment]
OK, I support that. The Data Hubs team did not care to explain to me why `/apihub` exists, so it does not seem to matter much to them, which endpoint we hit.

**Comment by Fernerkundung** [comment]
> why `/apihub` exists

When the Hub launched the endpoint `dhus` frequently was unavailable due to high load, so they created a clone without the frontend specifically for API requests.

Since they are not taking care of frequent syncs and not documenting it my guess is that `apihub` is just kept alive because it is technical debt. 

In any case, switching back over is trivial and can be remarked on in our docs. I'll create a PR as a minor change.

**Comment by iled** [comment]
Hi,

I'm a new Sentinel user and I just found this.

Since this issue is still open, I would like to leave here some of comments about this:

1. The endpoint `apihub` is the one described in the official docs: https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription
This link is accessible right through the [homepage](https://scihub.copernicus.eu) (see *API Hub*)

2. The *delay* is documented in the same link above.

3. Both endpoints are mentioned in the user guide:
https://scihub.copernicus.eu/userguide/ODataAPI

> OData Service Root URI for the Open Access Hub:
> - `https://scihub.copernicus.eu/dhus/odata/v1`
>
> OData Service Root URI for the API Hub:
> - `https://scihub.copernicus.eu/apihub/odata/v1/`

Since the endpoint `apihub` is the one they refer to specifically for accessing through the API, perhaps it is more appropriate to leave it as the default endpoint. The other endpoint may still be included in the docs.

**Comment by thomasyoung-audet** [comment]
Is there any consensus on what should be done here? Do we want to change the endpoint or not. The delay is mentioned in the sentinelsat docs in the Common issues. Is this enough? Should this issue be closed?

**Comment by j08lue** [comment]
Thanks for the bump, @thomasyoung-audet.

> Is this enough? Should this issue be closed?

Yes.

Also, `/dhus` is really not meant for machine use and it now raises 429 (too many requests) when you hit it too frequently from a script. So we stick to the official endpoint for machine access, which is `/apihub`.

**Comment by MrChebur** [comment]
@j08lue Thanks for [https://scihub.copernicus.eu/apihub](https://scihub.copernicus.eu/apihub) link - it solve my 429 too many requests problem.
