### ISSUE TITLE
Offline Data

### ISSUE THREAD

**Issue by Waasil** [sentinelsat/sentinelsat#271]
Hello,

I don't know how to write a private message to so I decided to write here.
Lately I have noticed that part of data on Sci-Hub became offline. I have found more information about that here: https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/LongTermArchive#Management_of_offline_products_v

This could be helpful information for you.

**Comment by Fernerkundung** [comment]
This has been fixed with #267, which was merged into the master branch but has yet to be published as a PyPi package.

**Comment by andretheronsa** [comment]
Thanks everyone for the fix - I am ready to check the Odata Online key before attempting to download data.
@Fernerkundung Is there an ETA on the PyPi package that includes this fix? I would prefer to wait for the package rather than cloning the repo, but if it will take weeks then I need to make a plan for our operational work.

**Comment by Fernerkundung** [comment]
@andretheronsa I should find some time tomorrow or later this week to bundle up a new release.

**Comment by Fernerkundung** [comment]
@andretheronsa v0.13 has just been released
