### ISSUE TITLE
Adding support to get s3 paths for the products returned

### ISSUE THREAD

**Issue by Fa7C0n** [sentinelsat/sentinelsat#278]
it would help a lot for someone who wants to run their processing pipeline inside aws infrastructure. When a user wants to process a particular product they can simply pass a flag or options like `--s3` or `s3path : True` then the api should return the s3 path associated with that particular product/tile. 

With this feature user can directly use `boto3` or something similar to get the image directly from the s3 instead of building the s3 path from the product title.

**Comment by j08lue** [comment]
I don't know. There are a bunch of tools already available for querying and downloading from the AWS S3 buckets https://github.com/Fernerkundung/awesome-sentinel/#search--download 

Since we query the SciHub / some other dhus catalogue, the S3 URLs we generate might not actually exist - they most probably will, but there is no guarantee.

So I think this is beyond our scope. But if you have a little utility function that generates S3 URLs from the metadata that our `api.query` returns, please share it and we could consider to add it to the docs.

What do the other maintainers think?

**Comment by Fernerkundung** [comment]
This would be a no from my side. `sentinelsat` is aimed at interfacing the DHuS instances, i.e. the Copernicus Open Access Hub, Collaborative Hub, most national Mirrors, etc.

The re-hosting of Sentinel data on Google's or AWS' services is usually limited to a subset of the Sentinel satellite constellations. e.g. how would we create a s3 path for for a Sentinel-5P query?

Furthermore, the re-hosted data might be reprocessed, renamed, etc. - therefore automatic creation of the URLs might be difficult as well.

Improving the search of Sentinel data on AWS and GCP would be better suited by different tools, e.g. DevelopmentSeed's [`sat-api`](https://github.com/sat-utils/sat-api) which creates a Spatio-Temporal Asset Catalogue (STAC) from data hosted on s3.

**Comment by Fernerkundung** [comment]
Closed as out-of-scope.
