### ISSUE TITLE
Ability to download only specific files from products

### ISSUE THREAD

**Issue by thhomas** [sentinelsat/sentinelsat#291]
I was interesting in downloading only specific band of Sentinel-2 product and I chose to insert this option in your tool.

I [forked](https://github.com/thhomas/sentinelsat) the project and made a get_product_manifest function using information given by [manifest file](https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/ODataAPI#Download_manifest_file_knowing_t). I chose to add an optional `band_list` option to `download` and `download_all` functions. It is only available to Sentinel-2 and not generic. 
The manifest is only available for S1 et S2 products and the band concept only concerns S2. I am not familiar with S1 products but I think we could easily extend this ability?
Are you interested in a pull request?

**Comment by valgur** [comment]
I'm not sure how common this specific use case is since I have not worked with S2 data much but it seems useful enough to include it.
The code you added looks good and well-documented, which is much appreciated. I would maybe refactor a couple of things:

- Add separate methods to the Python API that handle fetching files from inside the product archives via the OData API, e.g. methods for retrieving the file content, for downloading and saving them to disk and perhaps something like `os.listdir()` that lists the files available at a given path. All of methods would take a normal-looking file paths, such as `/GRANULE/L1C_.../IMG_DATA/..._B01.jp2`, as input. Your added functionality could then rely on these methods instead, making the code a bit tidier.
- Move the band-related code in `download()` to a sub-method, since it is not really the main task of the `download()` method and looks a bit confusing/cluttered.
- You are using f-strings for formatting, which is incompatible with Python < 3.6. We currently try to support Python 2.7 and 3.4+.

All in all, this looks like a very nice addition and I definitely encourage you to open a pull request.

**Comment by j08lue** [comment]
I second all of @valgur's comments - very thorough implementation. Open questions for me:

1. Should we really make the OData functionality part of the `SentinelAPI` class or make a subclass or separate implementation?
2. Is this maybe the time to go from one module in the package to several, like `sentinelsat.odata`?

**Comment by thhomas** [comment]
Thinking of your first point @valgur and I could easily create `get_product_file_list`, `download_product_file` and `get_product_file_content` methods.
It could be a first step but it makes me want to create something like a Product class with all these methods. 
As @j08lue said, it could be time to "break" the monolithic sentinel.py file.

**Comment by valgur** [comment]
@thhomas Moving the new functionality (and some of the old as well) under a Product class sounds perfect. I'm wondering if it might even make sense to make `.download()` a method of Product as well and maybe return query results as Products, but I don't feel like it would make the Python API more convenient to use.
Anyway, I encourage you to create the Product class with the methods you listed, plus the existing `get_product_odata()`. Don't feel pressured though, I can lend a hand here as well, if you wish.

**Comment by thhomas** [comment]
I started the refactoring work [here](https://github.com/thhomas/sentinelsat/tree/refactoring).
As it represents a big change in code, I would need feedback.
And I will definitely need help to rewrite tests as I am not familiar with pytest-vcr.

**Comment by martincornejo** [comment]
Is this functionality available (on the master branch)? I would only need to download the TCI in 10m resolution (for L2A)

**Comment by j08lue** [comment]
> Is this functionality available (on the master branch)? I would only need to download the TCI in 10m resolution (for L2A)

No, we never got all the way to including this. You can try to install the OP's fork and see if that still works. Otherwise, consider getting the files you need from the AWS Sentinel-2 bucket (which will cost a few $$ though), perhaps using [`sentinelhub-py`](https://sentinelhub-py.readthedocs.io/en/latest/examples/aws_request.html).
