### ISSUE TITLE
api.download_all fails silently when given a generator

### ISSUE THREAD

**Issue by andrewcooke** [sentinelsat/sentinelsat#336]
i guess this is pretty obscure, but it was surprising / annoying.

if download_all is passed a generator as the list of ids, it returns all empty values. 

the obvious fix from the user point of view is to use a force evaluation of the generator into a list.  but i think it's fair to say most modern python apis will accept generators or iterables or whatever for collections.

anyway, no biggie but thought you might want to fix it.

this is for version 0.13 using python 3.7.4 on linux.

**Comment by andrewcooke** [comment]
in fact, looking at the code, there is a trivial fix - replace `products` with `product_ids` (line 599 of sentinel.py 0.13)

**Comment by j08lue** [comment]
I believe this is already fixed in current `master`. At least I can see no reference to `products` anywhere in `download_all`, only `product_ids`. 

Could you please `pip install https://github.com/sentinelsat/sentinelsat/archive/master.zip` and see if you still have that issue? If you do, please feel free to submit a PR.

Note to self: we should really make a new release...

**Comment by andrewcooke** [comment]
oh you're right; sorry should have looked at master.
i'll try to run a test when my own code is back to normal.  but i am pretty sure things are fine so if i never reply again just close this.

**Comment by j08lue** [comment]
> if i never reply again just close this.

When is never, then? 😄 Let's say you re-open it if the problem still exists.

**Comment by andrewcooke** [comment]
apart from needing `--upgrade` with pip, that all worked fine.  the latest version works with generators.
