### ISSUE TITLE
Support for kml

### ISSUE THREAD

**Issue by eamanu** [sentinelsat/sentinelsat#343]
Hi everybody,

I am very very new on sentinelsat. But I am curious about the possibility
to support KML format in addition to  geojson?

**Comment by Fernerkundung** [comment]
The `sentinelsat` project aims to be lightweight on it's dependencies. Can you propose a library that supports the reading/conversion of KML files in Python?

- pyKML depends on 2 C libraries
- fastkml might work without C dependencies https://github.com/cleder/fastkml

**Comment by j08lue** [comment]
Can we solve this somehow else than adding a KML parser? Since KML is such a loose format, you would either need to handle a lot of cases or fail at many, I guess. 

It is not difficult - I wrote something that works ok using LXML at some point https://github.com/DHI-GRAS/kmlgeom - but I still think we should not add that kind of specific boilerplate to the library. Maybe just some pointers in the docs or so...

But still, perhaps rather write a pointer in the docs to how to solve this, rather than

**Comment by Fernerkundung** [comment]
From a UX perspective I would probably prefer that our CLI supports direct input of WKT or GeoJSON strings. Then you can chain it with any tool you like. 
e.g. by chaining Fionas CLI `fio` (https://fiona.readthedocs.io/en/latest/cli.html) `fio info` returns a GeoJSON.

**Comment by Fernerkundung** [comment]
Superseded by  #355. After this is implemented you can pipe GeoJSON strings into the CLI. Getting these from a KML would be possible by using [togeojson-cli](https://github.com/tmcw/togeojson-cli) or [fio info](https://fiona.readthedocs.io/en/latest/cli.html#info).
