### ISSUE TITLE
HTTP status 500 Internal Server Error: Trying to download an offline product

### ISSUE THREAD

**Issue by diogocaribe** [sentinelsat/sentinelsat#344]
Why any images returned this the answer below?
```
Trying to download an offline product
HTTP status 500 Internal Server Error: Trying to download an offline product
```
It is because they were removed from ESA data hub and we will never pick them up?

**Comment by j08lue** [comment]
https://sentinelsat.readthedocs.io/en/stable/api.html#lta-products

**Comment by lauraset** [comment]
Hi, I used the api.download_all() function to retrieve offline sentinel data, but it always return the message "_HTTP status 500 Internal Server Error: Trying to download an offline product_".

However, according to the instruction accessed by https://scihub.copernicus.eu/userguide/LongTermArchive, Http status code 202 should be returned if the request  has been successfully forwarded to the LTA. 

So does this mean the request is not forwarded to the LTA when the code 500 is returned?

Best regards,
Yinxia Cao

**Comment by Fernerkundung** [comment]
Which version of `sentinelsat` are you using? Latest from PyPi with `pip install` or the current master branch from Github?

LTA retrieval is supported, so it should work. However, the retrieval does take some time from the server.

**Comment by lauraset** [comment]
I use pip install sentinelsat

**Comment by Fernerkundung** [comment]
LTA retrieval is not released yet, but available in the master branch. You can download this repository and then perform `python setup.py install` to get that feature.

We will create a new release soon.

**Comment by lauraset** [comment]
Thank you very much

2020-04-08 

yinxcao 



发件人：Kersten <notifications@github.com>
发送时间：2020-04-06 22:42
主题：Re: [sentinelsat/sentinelsat] HTTP status 500 Internal Server Error: Trying to download an offline product (#344)
收件人："sentinelsat/sentinelsat"<sentinelsat@noreply.github.com>
抄送："YinxiaCao"<yinxcao@163.com>,"Comment"<comment@noreply.github.com>

LTA retrieval is not released yet, but available in the master branch. You can download this repository and then perform python setup.py install to get that feature.
We will create a new release soon.

**Comment by smetsb** [comment]
I have the same issue that my LTA request returns HTTP 500 instead of 202, using sentinelsat v0.13 (installed with pip install). There is no more information what went wrong in the return 500, so how can I proceed ?

Example of failure (note this happens for many files I'm trying to download from LTA):
DEBUG:urllib3.connectionpool:https://cophub.copernicus.eu:443 "GET /dhus/odata/v1/Products('5cbb9774-4111-470c-86ef-9ee2cc4d40b3')?$format=json HTTP/1.1" 200 None
INFO:sentinelsat.SentinelAPI:Downloading 5cbb9774-4111-470c-86ef-9ee2cc4d40b3 to /data/cel_vol1/HRL_PHENO/S2/S2_TOA/33UVS/S2B_MSIL1C_20190228T101029_N0207_R022_T33UVS_20190228T125729.zip
WARNING:sentinelsat.SentinelAPI:Product 5cbb9774-4111-470c-86ef-9ee2cc4d40b3 is not online. Triggering retrieval from long term archive.
DEBUG:urllib3.connectionpool:https://cophub.copernicus.eu:443 "GET /dhus/odata/v1/Products('5cbb9774-4111-470c-86ef-9ee2cc4d40b3')/$value HTTP/1.1" 500 0
ERROR:sentinelsat.SentinelAPI:Trying to download an offline product
>>> Exception
SentinelAPILTAError('Trying to download an offline product', <Response [500]>)
