### ISSUE TITLE
Display DHuS version in CLI

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#350]
Beginner friendly feature:

- #342 introduced a function to get the DHuS server-side version
- add a command-line entry with `click` to surface that version to CLI users
- name to be discussed, e.g. `sentinelsat --dhus-version`

Discussion:
- Is this too specialized to be added to the CLI and just clutters the arguments?
- Could this be aggregated to a `--info` argument that shows an overview of information of the DHuS server, capabilities, LTA, etc.?

**Comment by thomasyoung-audet** [comment]
Hi, I'm new to contributing and have a some questions about how you run tests. 
I've written the required code for this feature to function, but don't know how to go about testing it. 
I see you use prerecorded responses from the open access hub. Where would I add my own? do I even need to add my own because the `_req_dhus_stub()` function was already written, and all I'm doing is displaying what it gives me.

Right now the way its written it's just `sentinelsat --dhusversion` (the dash was causing problems). Do you want it aggregated into an `--info` argument?

**Comment by j08lue** [comment]
Great, @thomasyoung-audet, how about opening a pull request that we can use to discuss technical details?

There are a few, very brief notes on how to use vcrpy to record new cassettes. But if that is too involved, just make sure your tests work without the vcrpy part and we can help you add that. https://github.com/sentinelsat/sentinelsat#tests
