### ISSUE TITLE
Error during request

### ISSUE THREAD

**Issue by diogocaribe** [sentinelsat/sentinelsat#353]
Some days ago, the request works fine, but now I don't know what had happened. 

`HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /dhus/odata/v1/Products('49ce6743-9eeb-4eeb-acb4-82fa689dcb49')?$format=json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f016a7c0d50>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by j08lue** [comment]
Don't know about time out errors. That could be anything from their server to your software.

By the way, you are not supposed to run machine requests against `/dhus`. SciHub now heavily limits request frequency. But when that is the issue, you get a `429 Too Many Requests` error, so that is not your problem here. Still worthwile to try `/apihub`, though.

**Comment by diogocaribe** [comment]
Is there other place where can I download .SAFE file without paying?

**Comment by Fernerkundung** [comment]
Broadly speaking - yes, of course. Any other instance of a DHuS, like scihub.copernicus.eu/apihub or any of the other portals (example list https://github.com/Fernerkundung/awesome-sentinel)

**Comment by machf** [comment]
Hi, Can you kindly help me on this:

**Comment by machf** [comment]
Hi, Can you kindly help me on this: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /apihub/search?format=json&rows=100&start=0&q=beginPosition%3A%5B%222019-05-01T00%3A00%3A00Z%22+TO+%222019-05-31T00%3A00%3A00Z%22%5D+filename%3AS1A_%2A+orbitdirection%3A%22DESCENDING%22+platformname%3A%22Sentinel-1%22+producttype%3A%22GRD%22+sensoroperationalmode%3A%22IW%22+footprint%3A%22Intersects%28GEOMETRYCOLLECTION%28POLYGON%28%28100.2118+38.6801%2C100.5606+38.6801%2C100.5606+39.0459%2C100.2118+39.0459%2C100.2118+38.6801%29%29%29%29%22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027E909C6B88>: Failed to establish a new connection: [WinError 10060]

**Comment by j08lue** [comment]
@machf Looks like an intermittent connection error. If it persists, please contact Copernicus EO support. But please open new issues with descriptive titles.
