### ISSUE TITLE
Download Sentinel 2 TCI images from SciHub

### ISSUE THREAD

**Issue by webmap2015** [sentinelsat/sentinelsat#382]
Hi,

I want to download only "TCI.jp2 file just like "https://github.com/DHI-GRAS/s2-tci".

Is it possible?

Thanks.

**Comment by j08lue** [comment]
You just need to somehow construct the complete URL to the TCI file inside the .SAFE product. In the library you linked to, we parsed the XML documents returned by the DHuS query URL and tried to get the link from there. 

https://github.com/DHI-GRAS/s2-tci/blob/c656d5f224601295d3b344fab4c97653e1ddee8f/s2_tci/find.py#L9-L23

Because the querying is so slow, we used multithreading. https://github.com/DHI-GRAS/s2-tci/blob/c656d5f224601295d3b344fab4c97653e1ddee8f/s2_tci/chain.py#L26

I do not know whether the code still works. Please report if you try it. Perhaps you can also construct the full URL from the metadata, then you can get this done in a very few lines. Anyways, it all starts with a `sentinelsat` query, which gives you the base URL to the product.
