### ISSUE TITLE
--name overrides -s and -e?

### ISSUE THREAD

**Issue by pgallego96** [sentinelsat/sentinelsat#387]
Hi all, hopefully I can get some help with this.

I'm trying to download T32PLT Sentinel 2 images using sentinelsat for the period of 04/03/2019 and 27/02/2020. I'm using the code underneath:

`sentinelsat -u username -p password --start '20190304' --end '20200227' --name '*_T32PLT_*' --sentinel 2 --download --path '/path/to/folder'`

Unfortunately this seems to download every single T32PLT image to have ever existed in the archive, and the --start and --end don't seem to affect this at all. Having the same issue with Sentinel 1 by specifying:

 `--name 'S1A_IW_SLC*'`

Any suggestions are appreciated.

**Comment by valgur** [comment]
You can use `-q 'identifier=*_T32PLT_*'` instead.
When adding the `--name` option, I intended it to be used to query a list of specific products rather than wildcards and the default `NOW-1DAY` to `NOW` date filter was more of a hinder than of help, so I did not include them in that query. In hindsight, that was not a good choice.
Another somewhat unrelated issue with the `--name` option is that it creates a queries like `identifier:(name1 OR name2 OR name3 ...)` and the server-side behavior for more complex queries involving logical operators or even just parentheses, has become exceptionally slow. That is, up to tens of seconds per query rather than the more typical < 100 ms response time. So currently I would recommend avoiding `--name` altogether even if it should work.

**Comment by pgallego96** [comment]
Many thanks valgur for the quick reply! That solves my issue.

**Comment by Fernerkundung** [comment]
@valgur Do we want to reopen this for a improvement of the `--name` feature?

**Comment by valgur** [comment]
Yes, I think the `--name` behavior needs improvement.
