### ISSUE TITLE
Download fails (related to issue #393)

### ISSUE THREAD

**Issue by MargaridaBSC** [sentinelsat/sentinelsat#394]
Dear Sentinelsat Team,

Following the instructions of the closed issue #393, I send the solicited information:

- Python version: 3.6

- Sentinelsat version: 0.14

- OS: Ubuntu 18.04.4 LTS, GNOME 3.28.2

- Full error traceback:

```
python3 << EOF
from sentinelsat.sentinel import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date
from time import sleep

# connect to the API
api = SentinelAPI('${user}', '${password}', 'https://scihub.copernicus.eu/dhus')

# search by polygon, time, and Hub query keywords
footprint = geojson_to_wkt(read_geojson('poly.geojson'))
products = api.query(footprint,
                     date = ('${y}${m}${d}', date(${y}, ${m}, ${d})),
                     platformname = 'Sentinel-2',
                     cloudcoverpercentage = (0, 5))
print(products)
sleep(30)

# download all results from the search
api.download_all(products)
EOF
done
++ seq 1 31
+ for d in $(seq 1 $numdays)
+ python3
OrderedDict()
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sentinelsat/sentinel.py", line 811, in download_all
    raise next(iter(x.exception() for x in dl_tasks if x.exception()))
StopIteration
```
Please, let me know if you need more information and I'll be glad to send it to you.

Thank you very much.

Best regards,

Marga

**Comment by j08lue** [comment]
I just realized that @valgur recently opened a pull request that addresses this issue. #378 Maybe he could comment on what the real source of this exception is?

You could also try to install Sentinelsat from his branch and test with that: `pip install --upgrade https://github.com/valgur/sentinelsat/archive/270-incorrect-filename.zip`. That should solve Sentinelsat from breaking here but I do not know whether there are other issues.

**Comment by j08lue** [comment]
Turns out someone else had this issue. Judging from this comment https://github.com/sentinelsat/sentinelsat/issues/377#issuecomment-652973149, your issue might be that your query does not return any results and you pass an empty dictionary to `api.download_all`. So does `print(products)` show any products?

Actually, I am quite sure it does not, since you are search for `date=(date, date)`, where both dates are the same. Try searching for `date=(datetime.datetime(2020, 7, 30), datetime.datetime(2020, 7, 30, 23, 59, 59)` instead or something.

**Comment by MargaridaBSC** [comment]
Hi @j08lue,

You're a genious! Changing the dates worked like a charm. Thank you very much!!

All the best,

Marga
