### ISSUE TITLE
LTA retrieval: unable to differentiate between success (202) and quota exceeded (403)

### ISSUE THREAD

**Issue by daniel-j-h** [sentinelsat/sentinelsat#400]
Hey folks :wave: 

when a product is offline, we trigger a long term archive retrieval.

When this retrieval request fails hard e.g. with a 503 or 500 response code, we throw an `SentinelAPILTAError` exception.

But when we successfully trigger a retrieval (200) _or when we hit the quota limit_ (403) we do not throw an exception but only return the status code. But then in the download function, we never use this returned status code or tell the user about this.

Ideally we'd notify the user in case the quota limit is exceeded.

Right now there is no way using `.download()` to differentiate between successful LTA retrieval and error due to the exceeded quota.

https://github.com/sentinelsat/sentinelsat/blob/a070cc02919d50b661858a7b1b217fff7e8e6222/sentinelsat/sentinel.py#L643-L674

https://github.com/sentinelsat/sentinelsat/blob/a070cc02919d50b661858a7b1b217fff7e8e6222/sentinelsat/sentinel.py#L586-L593

**Comment by gbaier** [comment]
Hi Daniel,

You're right. The current behavior leaves the user completely in the dark. I think there are a couple of things we could do.

1. Change **logger.debug** to **logger.warning**, or even higher when logging that the quota is exceeded
1. Check the status code at https://github.com/sentinelsat/sentinelsat/blob/a070cc02919d50b661858a7b1b217fff7e8e6222/sentinelsat/sentinel.py#L592
1. Advertise that users should use **download_all** instead of **download**, since it has more error-checking etc.
1. Raise a new custom exception.

Let's see what the others have to say.

**Comment by daniel-j-h** [comment]
It would be great if the callsite knows about it to act on it - changing the logging level is not sufficient in that case.

**Comment by Fernerkundung** [comment]
All good suggestions - one UX level question:

How do we differentiate the warning surfaced to the user in case of 1) wrong log-in credentials or 2) quota exceeded. Both return a 403 status code (wrongly in the second case arguably).

**Comment by valgur** [comment]
Should be fixed by the changes in #400. Feel free to re-open if that's not the case.
