### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#416]
Should we finally drop Python 2 support? It has been very little effort to keep it until now, but causes some trouble for example in #414 and I would say it has long been time to say goodbye...

**Comment by Fernerkundung** [comment]
+1 from my side. We have supported Python 2 for 1 year past it's EOL and it is time to move on - even for a lot of our scientific users this should have been adequate time to make any changes on their end.

Follow-up question: What is the minimumy Python 3 version we want to aim for? I'd propose 3.7 due to the improved type hints and async/await support. It also shadows the current requirements for numpy and therefore should be available on any system that scientific users want to use. I assume all other users have upgraded a long time ago anyway.

https://docs.python.org/3/whatsnew/3.7.html

**Comment by valgur** [comment]
Based on https://pypistats.org/packages/sentinelsat 3.6 is still somewhat common, the older versions not so much. So I would suggest picking 3.6 as the minimum required version.

**Comment by j08lue** [comment]
Nice. >3.6 it is.

Can you please also indicate what you think of PR #414, so we can get on with that, @valgur and @Fernerkundung?
