### ISSUE TITLE
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by MrChebur** [sentinelsat/sentinelsat#519]
```
download_result = sci_hub_api.download(product_id, directory_path=target_folder, checksum=True)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\sentinelsat\sentinel.py", line 527, in download
self._download_outer(product_info, path, checksum)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\sentinelsat\sentinel.py", line 564, in _download_outer
temp_path.parent.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'
```
Indeed, [os.mkdir](https://docs.python.org/3/library/os.html#os.mkdir) has no such keyword, while [os.makedirs]( https://docs.python.org/3/library/os.html#os.makedirs) does.

Python ver. = 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

**Comment by valgur** [comment]
Not sure what's going on here... that line is using [`pathlib.Path.mkdir`](https://docs.python.org/3/library/pathlib.html?highlight=pathlib%20mkdir#pathlib.Path.mkdir) rather than `os.mkdir` as you suggested. Also, that bit of code is covered by unit tests without encountering any issues. The only cause I can think of is that you have an extremely old Python 3.4 somewhere on your Python path, but that seems unlikely.

**Comment by MrChebur** [comment]
@valgur Thanks for the answer. I will close this issue pending further investigation.

**Comment by MrChebur** [comment]
For those who have encountered the same problem.The error was caused by the presence of two pathlib.py filesin the folders:
1) C:\OSGeo4W\apps\Python39\Lib\site-packages
2) C:\OSGeo4W\apps\Python39\Lib

After removing `C:\OSGeo4W\apps\Python39\Lib\site-packages` the problem was solved.
