### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by JeffHCross** [sentinelsat/sentinelsat#546]
I'm running into this error when trying to call api.query the last couple weeks. I assume it has something to do with the [Let's Encrypt R3 cert](https://community.letsencrypt.org/t/windows-python-urlopen-certificate-verify-failed/162783) that [expired last month](https://stackoverflow.com/questions/69397039/pymongo-ssl-certificate-verify-failed-certificate-has-expired-on-mongo-atlas), but I've followed the instructions to install the new certificates into the Windows store and still am unable to get Python to use the correct certs. I assume at this point it's either a urllib or Python problem. My browser sees no issues with the apihub cert.  Any suggestions for resolution would be appreciated.

```
SSLError: HTTPSConnectionPool(host='apihub.copernicus.eu', port=443): Max retries exceeded with url: /apihub/search?
format=json&rows=100&start=0&q=beginPosition%3A%5B%222021-10-17T14%3A04%3A23Z%22+TO+%222021-10-
27T14%3A04%3A23Z%22%5D+cloudcoverpercentage%3A%5B%220%22+TO+%224%22%5D+platformname%3A%22Senti
nel-2%22+platformserialidentifier%3A%22Sentinel-2A%22+processinglevel%3A%22Level-
1C%22+footprint%3A%22Intersects%28POLYGON_REMOVED_FROM_ERROR (Caused by 
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify 
failed: certificate has expired (_ssl.c:1091)')))
```

**Comment by sidxdev** [comment]
I'm facing this same issue for scihub.copernicus.eu. It was not occurring last week but suddenly started popping up today.
I am using a Ubuntu 20.04 VM. I tried to run [update-ca-certificates](https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html) but that does not seem to work.

Any idea what could be the issue?

Note - I use scihub instead of default because default gives me random internal server errors many times.
