### ISSUE TITLE
filtering query by date returns results with partial coverage

### ISSUE THREAD

**Issue by scottstanie** [sentinelsat/sentinelsat#551]
Hi, this might be an issue stemming from a scihub decision, but do you know why when using the `date` filtering keyword, it would return results that don't fully cover the start and end time? This is happening even when the product that covers the whole requested window does exist.

```python
import datetime
from sentinelsat import SentinelAPI

t0 = datetime.datetime(2021, 12, 7, 9, 50, 15)
t1 = datetime.datetime(2021, 12, 7, 11, 50, 15)

api = SentinelAPI(user='gnssguest', password='gnssguest', api_url="https://scihub.copernicus.eu/gnss/")
results = api.query(producttype='AUX_RESORB', platformserialidentifier='1A', date=[t0, t1])

len(results)
# 1

results['d0759d2f-35f1-4581-bf5f-7cf08a4960fb']['beginposition']
datetime.datetime(2021, 12, 7, 10, 52, 44)

results['d0759d2f-35f1-4581-bf5f-7cf08a4960fb']['endposition'] > t1
# True
results['d0759d2f-35f1-4581-bf5f-7cf08a4960fb']['beginposition'] < t0
# False


```

Note that there does exist an orbit product that fully covers it... but it's not returned! If I move back the search window by an hour, it now returns 2. One of which covers the original time period I wanted, one does not (the same one that was returned above).

```python
t0_earlier = t0 - datetime.timedelta(hours=1)
results = api.query(producttype='AUX_RESORB', platformserialidentifier='1A', date=[t0_earlier, t1])


len(results)
# 2
results['920ddebb-8c16-40a2-afbd-0ce5c12876ae']['beginposition'] < t0
# True
results['920ddebb-8c16-40a2-afbd-0ce5c12876ae']['endposition'] > t1
True
```

**Comment by avalentino** [comment]
As far as I can understand the query should return all products (also partially) covering the time interval that you have specified.
I agree with you that the behavior is strange.
Unfortunately this kind of query cannot be replicated in the web interface.

**Comment by valgur** [comment]
That behavior is expected due to the `date` parameter in `query()` being just an alias for the `beginposition` attribute, which the server will then use for filtering.

You can construct a more exact query by using both `beginposition` and `endposition` to get
- only products that are entirely contained within (t0, t1):
```python
api.query(..., beginposition=(t0, None), endposition=(None, t1))
```
- all products that intersect with (t0, t1):
```python
api.query(..., beginposition=(None, t1), endposition=(t0, None))
```

Now that you mention it, it would not actually be a bad idea to make the `date` parameter in `api.query()` include the `endposition` value as well. We could perhaps make the "intersects" query the default and add a `date_relation` parameter that is analogous to `area_relation`:
```
area_relation : {'Intersects', 'Contains', 'IsWithin'}, optional
    What relation to use for testing the AOI. Case insensitive.
        - Intersects: true if the AOI and the footprint intersect (default)
        - Contains: true if the AOI is inside the footprint
        - IsWithin: true if the footprint is inside the AOI
```
