### ISSUE TITLE
serve sentinel tiles in frontend

### ISSUE THREAD

**Issue by aghand0ur** [sentinelsat/sentinelsat#594]
Hello,

This is quite off topic but I am wondering if you have plans to extend sentinelsat tool to provide WSM endpoint to serve sentinel tile in a front page (built using react for instance).

I was not able to find any free and open API to do that yet.
Am I missing something obvious?

Ali

cc @Louma20

**Comment by j08lue** [comment]
Serving satellite data for web maps is indeed out of scope for Sentinelsat, this project being about search and download of products from the Copernicus OData API.

Serving raster data for web maps is costly, which is probably why there are no free services.

If you want WM(T)S of Sentinel data as a (paid) service, check out [Sentinel Hub](https://www.sentinel-hub.com/develop/api/ogc/).

If you want to stand up your own map tiles service, there are several options, too. For example, the Python app [Terracotta](https://terracotta-python.readthedocs.io/) can serve map tiles (XYZ) from a bunch of files on disk or S3 with a few commands. [TiTiler](https://developmentseed.org/titiler/) is super quick to stand up to serve map tiles (XYZ or WMTS) from files object storage, for example the [Sentinel-2 COGs in AWS](https://registry.opendata.aws/sentinel-2-l2a-cogs/).

I hope you can find helpful resources below these links. I'll close this ticket, since it is out of scope for Sentinelsat.
