### ISSUE TITLE
Downloaded Images do not have a crs - linux only

### ISSUE THREAD

**Issue by taimoorh13** [sentinelsat/sentinelsat#595]
Hi, 
I was trying to use this package to download images in an automation pipeline. The package is very easy to use and good documentation. Anyways, I installed it on a _linux instance_ in GCP and tried downloading an image. Let me just quickly give a brief overview of what I am doing. I basically search the images using the '**uuid**'s of the sentinel image which I already have from another source/function(based on the date and the AOI). I then parse these uuids one by one to download the image (as per the code below). The image downloads as expected without any error but when I look into the metadata of the image, it **does not have a crs.** The crs is just 'None'. Thats why I cant perform other computations on this image such as clipping the images. I cant also define the crs by myself because the image does not necessarliy cover an AOI in a similar region. It actually spans a complete country and can be of any location within the country. I also saw that when I download the images manually from scihub, they have a crs that is according to the AOI. If it only downloaded on one default crs for any AOI, that would have been no issue as I could have assigned a crs after download but thats not the case (I think). Maybe you can help identify the issue if its in the source code or something else. 

**Important note**:
I initially created the script on a windows machine and tested it there before using it on the instance. The script worked perfectly on the that machine without any issue of the crs. I only started getting the issue in last 2 weeks because it was also running fine on the instance 2 weeks ago. Just now, it has this issue. I always download the latest image available for the AOI (maybe thats causing the issue, I am not sure, but it works fine on windows).

Here is a uuid using which you can test it
product_id = _T38RPN_20230604T121754_

```
products = api.query(identifier = product_id, platformname='Sentinel-2')

# Convert the data returned by the API to a dataframe
products_df = api.to_dataframe(products)

# Check if the product is online
is_online = api.is_online(products_df.iloc[0]['uuid'])

# Create a filter to only download required band in this case band 4 and 8
path_filter = make_path_filter("*_B0[48]_10m.jp2")
    
 if is_online:
        api.download_all(products_df.index, nodefilter=path_filter)
```

**Comment by j08lue** [comment]
I am pretty sure this has nothing to do with Sentinelsat. Our library does not modify the files you download, it just pulls them off the server and dumps them on your disk. And there is no dependency on the operating system you are running this on.

However, CRS not getting read can come from a broken PROJ library and that can indeed be installation-specific - hence the different behaviour you experience between your two installations. 

Steps to verify this:
1. Cross-check: load an image you downloaded on one machine on the other
2. Re-install Rasterio or whatever you are loading the images with on your Linux machine. Installing with `pip` should be fine on Linux. See whether that fixes your CRS issue.

Again - my hunch is that your issue is with loading the files after you downloaded them, NOT with the download / Sentinelsat.

**Comment by taimoorh13** [comment]
Thanks for the quick reply and suggestion. 
Yes, I re-installed the rasterio package and it worked fine, the error vanished. It was strange because rasterio was working fine 8-10 days ago and I didnt even change the environment after that. Thats why I thought that the issue might be with linux only, but it was indeed with the rasterio package itself. Now that I think, it was naive of me to not try and re-install the package by myself, I just kept on trying to update the packages with no luck. 
Anyways, Thanks for the help, I appreciate it.
