### ISSUE TITLE
Future of sentinelsat with ramp-down of Copernicus Open Access Hub?

### ISSUE THREAD

**Issue by schckngs** [sentinelsat/sentinelsat#600]
Hey sentinelsat folks, thanks for making this great package that I have gotten a lot of use out of in the last few years 🙂
With the ramp-down of the Copernicus Open Access Hub, do you have plans for the future of this package?
Cheers,
-Andrea

**Comment by j08lue** [comment]
Thanks for the question, @schckngs. We kinda discuss that in #583 - but your question is still unanswered.

**Comment by schckngs** [comment]
Thanks @j08lue, hadn't seen that post. 
Missing this package as I try to figure out how to easily batch download Sentinel-2 data all over again! The `download_all_quicklooks()` functionality at least is still working fully as far as I can tell.

**Comment by j08lue** [comment]
> Missing this package as I try to figure out how to easily batch download Sentinel-2 data all over again!

Yeah, there is probably a case for continuing the brand of Sentinelsat as a download client - even if not the API.

A few alternatives have been mentioned in the other thread already - I only know this simple one works: https://github.com/DHI-GRAS/creodias-finder

**Comment by fpl** [comment]
I'm currently working on extending one project of mine (written mostly in Perl, sorry guys) to cope with the new OData, OSearch and RestO APIs. It is mainly compatible with my `scihub` script on github which is based on sentinelsat since years. That is basically to undestand novelties and limitations of the new APIs. For sure, now to get the same metadata once available in a single remote call, it is now required to call two different REST services for each product, because the OSearch is largely incomplete for Sentinels (no relative orbit number and no direction available, for instance). I'm quite mmmhh... perplexed, to be gentle. As a bouns, now an authenticated session is required only for download, apparently.
